# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4e9e166367e80c062d31c73303a085bc"
name = "CheckoutGuard"
application_url = "https://checkoutguardalerts.com"
embedded = false

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/create"
  topics = [ "orders/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_orders"

[auth]
redirect_urls = [ "https://checkoutguardalerts.com/auth/callback" ]
